apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
id: nhat-14-edge-app
metadata:
  name: edge app
  description: A basic edge app inspired by oomichi-melco
  version: 1.0.0
  catalog:
    organization:
      - name: nhat-14
        site: https://github.com/nhat-14
deploymentProfiles:
  - type: compose
    id: nhat-14-edge-app-compose-a
    components:
      - name: edge-app-docker
        properties:
          packageLocation: https://raw.githubusercontent.com/nhat-14/try-margo/refs/heads/main/try-margo/plugfest202607/apps/edge-app/docker-compose/compose.yaml